# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.7"
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"

matrix:
  fast_finish: true
  include:
    # DJANGO 1.11
    - python: 2.7
      env: DJANGO_VERSION=1.11
    - python: 3.4
      env: DJANGO_VERSION=1.11
    - python: 3.5
      env: DJANGO_VERSION=1.11
    - python: 3.6
      env: DJANGO_VERSION=1.11

    # DJANGO 2.0
    - python: 3.4
      env: DJANGO_VERSION=2.0
    - python: 3.5
      env: DJANGO_VERSION=2.0
    - python: 3.6
      env: DJANGO_VERSION=2.0
    - python: 3.7
      env: DJANGO_VERSION=2.0

    # DJANGO 2.1
    - python: 3.5
      env: DJANGO_VERSION=2.1
    - python: 3.6
      env: DJANGO_VERSION=2.1
    - python: 3.7
      env: DJANGO_VERSION=2.1

    # DJANGO 2.2.9
    - python: 3.5
      env: DJANGO_VERSION=2.2.9
    - python: 3.6
      env: DJANGO_VERSION=2.2.9
    - python: 3.7
      env: DJANGO_VERSION=2.2.9

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements_test.txt
  - pip install Django=="$DJANGO_VERSION"

# command to run tests using coverage, e.g. python setup.py test
script: coverage run --source django_json_widget runtests.py
# script: tox -e $TOX_ENV

# after_success:
#   - codecov -e TOX_ENV
